### ISSUE TITLE
index uppercase

### ISSUE THREAD

**Issue by Carlosgrr** [SilkAndSlug/minecraft-init#5]
I tried running the script to start the server and the console output the following error:
/etc/init.d/minecraft: line 1038: INDEX: unbound variable
From what I understand the problem here is that the $INDEX variable is supposed to be uppercase at the declaration, so i replaced all lowercase index on my script it and the game started as supposed.
Can you fix this or should I PR the changes?

**Comment by SilkAndSlug** [comment]
I don't use this script any more, and never finished fixing the bugs I inherited from my predecessors. Sadly, this fork is effectively abandoned. I now use EMSM.

I've pushed all my branches to GitHub, and you are (anyone is!) very welcome to merge them -- or not -- into another fork. Best wishes.

I've glanced at the code, and agree with your changes.
